### ISSUE TITLE
Cannot invoke initializer for type 'Range<String.Index>' with an argument list of type '(Range<String.Index>)'

### ISSUE THREAD

**Issue by fulminex** [StartAppsPe/StartAppsKitExtensions#2]
Cambiar por 'start..<self.endIndex' en StringExtensions
salu2

**Comment by gabriellanata** [comment]
Hola! Quieres contribuir al open source? Puedes generar un PR para cualquier repo en StartAppsKit y los reviso.

**Comment by gabriellanata** [comment]
Fixed in PR
